"""M0 -- the desk-verifiable half of eval 1: the Delta IK/FK *math*.

No Isaac, no GPU. This proves the kinematic core is exact so that when the rig
(isaac_plant.py) disagrees with fk() beyond the eval-1 tolerance, the fault is
provably the physics/rigging, not the math.
"""
import math

import numpy as np
import pytest

from deltahil.plant.delta_ik import (
    DEFAULT_DELTA_GEOM,
    DeltaGeom,
    Unreachable,
    fk,
    ik,
)

GEOM = DEFAULT_DELTA_GEOM


def _reachable_grid(geom: DeltaGeom):
    """Points generated by fk() from a joint grid are reachable by construction;
    round-tripping them exercises ik then fk over the real workspace."""
    pts = []
    angs = np.linspace(math.radians(-15), math.radians(55), 8)
    for a in angs:
        for b in angs:
            for c in angs:
                try:
                    pts.append(fk(geom, (a, b, c)))
                except Unreachable:
                    continue
    return pts


def test_ik_then_fk_recovers_point_below_1e6_mm():
    pts = _reachable_grid(GEOM)
    assert len(pts) > 200, "workspace sampling too sparse to be meaningful"
    worst = 0.0
    for p in pts:
        thetas = ik(GEOM, p)
        q = fk(GEOM, thetas)
        worst = max(worst, float(np.linalg.norm(np.asarray(q) - np.asarray(p))))
    assert worst < 1e-6, f"ik/fk round-trip error {worst:.3e} mm exceeds 1e-6"


def test_fk_then_ik_recovers_angles():
    # start from joint angles, fk to a pose, ik back -- angles must match
    for a in np.linspace(math.radians(-10), math.radians(50), 5):
        thetas = (a, a * 0.5, -a * 0.3 + math.radians(20))
        p = fk(GEOM, thetas)
        back = ik(GEOM, p)
        for t0, t1 in zip(thetas, back):
            assert abs(t0 - t1) < 1e-9, f"angle mismatch {t0} vs {t1}"


def test_home_pose_is_symmetric():
    # equal joint angles -> platform on the central Z axis (x=y=0)
    p = fk(GEOM, (math.radians(20), math.radians(20), math.radians(20)))
    assert abs(p[0]) < 1e-9 and abs(p[1]) < 1e-9
    assert p[2] < 0.0, "platform hangs below the base (z negative)"


def test_out_of_workspace_raises():
    with pytest.raises(Unreachable):
        ik(GEOM, (0.0, 0.0, -50.0))     # far too high, arms cannot reach
    with pytest.raises(Unreachable):
        ik(GEOM, (5000.0, 0.0, -700.0))  # far outside the radial envelope
